### ISSUE TITLE
Correctly pass all Rails Routing DSL options through api-versions

### ISSUE THREAD

**Issue by davidcelis** [EDMC/api-versions#16]
There are some instances where certain Rails routing options don't work from within api_namespaces. For example, #11 mentions the `:path` option being ignored from within `:shallow` routes and #12 brings up the point that we always set `:namespace` to `'api'`. We should handle these options better.

**Comment by k-rudy** [comment]
Hey guys, any plans to fix this issue? Any info on when it will be fixed?
