### ISSUE TITLE
Cut a new gem version to contain #6

### ISSUE THREAD

**Issue by Zorbash** [EDMC/api-versions#23]
54eaadb7 fixes a common bug where:

```bash
curl -i -XGET http://localhost:3000/api/bar/new \
     -H 'Accept: '
```

Would respond with a 500 due to: 

```
ERROR NoMethodError: undefined method `split' for nil:NilClass
	/home/zorbash/dev/gems/api-versions/lib/api-versions/version_check.rb:12:in `matches?'
```

A new gem version has to be released to contain the fix.

**Comment by davidcelis** [comment]
Hey @Zorbash, sorry for the wait. I've released version 1.2.1. One of these days I'll fix the build on Rails 4 :disappointed:
